# Class of the matching algorithm
matching.algorithm.class = com.riotgames.interview.hongkong.matchmaking.matcher.BasicSkillMatcher

# Class of the skill calculator algorithm
skill.calculator.class = com.riotgames.interview.hongkong.matchmaking.skill.BasicSkillCalculator