package com.riotgames.interview.hongkong.matchmaking;

import java.util.ArrayList;
import java.util.List;

import com.riotgames.interview.hongkong.matchmaking.player.Player;

public class SampleData {

    public static List<SamplePlayer> getSamplePlayers() {
        final List<SamplePlayer> players = new ArrayList<SamplePlayer>(250);

        players.add(new SamplePlayer("Kate Wells", 961, 658));
        players.add(new SamplePlayer("Kristine Newman", 852, 179));
        players.add(new SamplePlayer("Billie Roberts", 942, 951));
        players.add(new SamplePlayer("Ernestine Holloway", 61, 500));
        players.add(new SamplePlayer("Candace Reynolds", 235, 8));
        players.add(new SamplePlayer("Susan Potter", 234, 486));
        players.add(new SamplePlayer("Jessie Dawson", 910, 258));
        players.add(new SamplePlayer("Clint Massey", 647, 310));
        players.add(new SamplePlayer("Pamela Gross", 331, 599));
        players.add(new SamplePlayer("Roxanne Morrison", 235, 980));
        players.add(new SamplePlayer("Marjorie Tyler", 746, 570));
        players.add(new SamplePlayer("Jeanette Bass", 909, 612));
        players.add(new SamplePlayer("Guadalupe Saunders", 820, 430));
        players.add(new SamplePlayer("Laura Barton", 908, 422));
        players.add(new SamplePlayer("Simon Ingram", 99, 842));
        players.add(new SamplePlayer("Dewey Fitzgerald", 3, 328));
        players.add(new SamplePlayer("Rickey Lindsey", 665, 181));
        players.add(new SamplePlayer("Harold Grant", 820, 70));
        players.add(new SamplePlayer("Irvin Moody", 433, 98));
        players.add(new SamplePlayer("Hannah Sullivan", 0, 499));
        players.add(new SamplePlayer("Clark Jones", 986, 424));
        players.add(new SamplePlayer("Jamie Parks", 371, 215));
        players.add(new SamplePlayer("Sherri Thomas", 266, 33));
        players.add(new SamplePlayer("Constance Day", 519, 661));
        players.add(new SamplePlayer("Mae Mathis", 919, 165));
        players.add(new SamplePlayer("Pam Alexander", 30, 784));
        players.add(new SamplePlayer("Fannie Rios", 625, 162));
        players.add(new SamplePlayer("Darrell Howard", 145, 457));
        players.add(new SamplePlayer("Kathy Green", 675, 546));
        players.add(new SamplePlayer("Elisa Hunt", 985, 296));
        players.add(new SamplePlayer("Ricardo Rivera", 224, 289));
        players.add(new SamplePlayer("Karen Reese", 641, 660));
        players.add(new SamplePlayer("Roderick Jimenez", 754, 378));
        players.add(new SamplePlayer("Abel Cruz", 739, 104));
        players.add(new SamplePlayer("Clay Adams", 93, 813));
        players.add(new SamplePlayer("Frank Nash", 102, 781));
        players.add(new SamplePlayer("Jackie Allison", 162, 199));
        players.add(new SamplePlayer("Celia Garcia", 485, 918));
        players.add(new SamplePlayer("Sheldon Martin", 104, 29));
        players.add(new SamplePlayer("Rex Clarke", 891, 468));
        players.add(new SamplePlayer("Ross Castillo", 229, 230));
        players.add(new SamplePlayer("Mathew Park", 650, 310));
        players.add(new SamplePlayer("Pat Allen", 347, 365));
        players.add(new SamplePlayer("Luke Perkins", 460, 972));
        players.add(new SamplePlayer("Kurt Obrien", 733, -760));
        players.add(new SamplePlayer("Pedro Stokes", 264, 360));
        players.add(new SamplePlayer("Sophia Butler", 976, 376));
        players.add(new SamplePlayer("Elaine Gregory", 630, 994));
        players.add(new SamplePlayer("Eduardo Patrick", 479, 837));
        players.add(new SamplePlayer("James Drake", 350, 487));
        players.add(new SamplePlayer("Rogelio Caldwell", 174, 612));
        players.add(new SamplePlayer("Stephanie Sutton", 770, 925));
        players.add(new SamplePlayer("Mike Harmon", 656, 544));
        players.add(new SamplePlayer("Lorene Wolfe", 235, 166));
        players.add(new SamplePlayer("Irving Houston", 852, 11));
        players.add(new SamplePlayer("Valerie Watson", 961, 22));
        players.add(new SamplePlayer("Maggie Cortez", 242, 887));
        players.add(new SamplePlayer("Johnnie Wallace", 965, 514));
        players.add(new SamplePlayer("Anna Mckenzie", 628, 894));
        players.add(new SamplePlayer("Wesley Carroll", 608, 343));
        players.add(new SamplePlayer("Tara Harvey", 631, 138));
        players.add(new SamplePlayer("Jo Ramos", 839, 868));
        players.add(new SamplePlayer("Cary Pierce", 673, 586));
        players.add(new SamplePlayer("Ellen Beck", 502, 990));
        players.add(new SamplePlayer("Kristin Watts", 892, 57));
        players.add(new SamplePlayer("Lewis Johnston", 960, 38));
        players.add(new SamplePlayer("Denise Warner", 248, 100));
        players.add(new SamplePlayer("Marcos Freeman", 601, 608));
        players.add(new SamplePlayer("Joshua Chapman", 447, 880));
        players.add(new SamplePlayer("Johnnie Carter", 643, 563));
        players.add(new SamplePlayer("Nichole May", 98, 590));
        players.add(new SamplePlayer("Bernard Mckinney", 212, 112));
        players.add(new SamplePlayer("Robin Richardson", 546, 149));
        players.add(new SamplePlayer("Fernando Warren", 169, 57));
        players.add(new SamplePlayer("Carl Snyder", 336, 554));
        players.add(new SamplePlayer("Ramon Huff", -99, 639));
        players.add(new SamplePlayer("Felipe Silva", 245, 685));
        players.add(new SamplePlayer("Della Rose", 864, 192));
        players.add(new SamplePlayer("Jake Baker", 573, 379));
        players.add(new SamplePlayer("Jennifer Tran", 493, 435));
        players.add(new SamplePlayer("Earnest Hicks", 358, 652));
        players.add(new SamplePlayer("Traci Harrington", 103, 569));
        players.add(new SamplePlayer("Justin Powers", 264, 769));
        players.add(new SamplePlayer("Lindsey Simpson", 985, 330));
        players.add(new SamplePlayer("Desiree Rhodes", 876, 324));
        players.add(new SamplePlayer("David Johnson", 191, 473));
        players.add(new SamplePlayer("Lois Mann", 206, 547));
        players.add(new SamplePlayer("Cesar Yates", 121, 325));
        players.add(new SamplePlayer("Rachael Lee", 839, 450));
        players.add(new SamplePlayer("Jeff Quinn", 259, 77));
        players.add(new SamplePlayer("Olive Bush", 755, 220));
        players.add(new SamplePlayer("Mandy Russell", 401, 672));
        players.add(new SamplePlayer("Mildred Rogers", 618, 718));
        players.add(new SamplePlayer("Peter Myers", 432, 358));
        players.add(new SamplePlayer("Austin Chavez", 442, 576));
        players.add(new SamplePlayer("Alex Bowers", 200, 854));
        players.add(new SamplePlayer("Teresa Cannon", 801, 857));
        players.add(new SamplePlayer("Antonia Lloyd", 741, 876));
        players.add(new SamplePlayer("Melba Ford", 936, 37));
        players.add(new SamplePlayer("Lynda Maldonado", 853, 398));
        players.add(new SamplePlayer("Kelly Steele", 979, 766));
        players.add(new SamplePlayer("Rosemarie Christensen", 52, 700));
        players.add(new SamplePlayer("Sandy Warner", 740, 261));
        players.add(new SamplePlayer("Christie Ward", 122, 707));
        players.add(new SamplePlayer("Julie Henderson", 792, 155));
        players.add(new SamplePlayer("Loretta Fletcher", 615, 92));
        players.add(new SamplePlayer("Yvonne Ferguson", 450, 216));
        players.add(new SamplePlayer("Ruth Soto", 669, 85));
        players.add(new SamplePlayer("Virginia Tyler", 939, 743));
        players.add(new SamplePlayer("Jenna Stokes", 787, 563));
        players.add(new SamplePlayer("Michele Reed", 107, 228));
        players.add(new SamplePlayer("Horace Barber", 666, 490));
        players.add(new SamplePlayer("Ralph Ray", 624, 51));
        players.add(new SamplePlayer("Ana Clarke", 743, 228));
        players.add(new SamplePlayer("Donna Harmon", 781, 247));
        players.add(new SamplePlayer("Laura Black", 113, 697));
        players.add(new SamplePlayer("Clyde Chapman", 487, 243));
        players.add(new SamplePlayer("Cory Bishop", 565, 241));
        players.add(new SamplePlayer("Grant Chandler", 801, 952));
        players.add(new SamplePlayer("Brenda Davis", 966, 587));
        players.add(new SamplePlayer("Roderick Bailey", 71, 204));
        players.add(new SamplePlayer("Lester Tucker", 280, 353));
        players.add(new SamplePlayer("Arturo Goodman", 919, 19));
        players.add(new SamplePlayer("Pedro Mccormick", 43, 491));
        players.add(new SamplePlayer("Lee Potter", 131, 133));
        players.add(new SamplePlayer("Kristine Mann", 340, 852));
        players.add(new SamplePlayer("Mack Gonzales", 27, 692));
        players.add(new SamplePlayer("Patrick Mills", 751, 268));
        players.add(new SamplePlayer("Ian Poole", 128, 479));
        players.add(new SamplePlayer("Daniel Moss", 553, 523));
        players.add(new SamplePlayer("Ann Owen", 9223372036854775807L, 56));
        players.add(new SamplePlayer("Antoinette Fuller", 242, 879));
        players.add(new SamplePlayer("Flora Webster", 76, 191));
        players.add(new SamplePlayer("Meghan Lawson", 952, 747));
        players.add(new SamplePlayer("Traci Harris", 687, 809));
        players.add(new SamplePlayer("Moses Walters", 678, 252));
        players.add(new SamplePlayer("Cary Stone", 544, 521));
        players.add(new SamplePlayer("Deborah Nelson", 891, 736));
        players.add(new SamplePlayer("Julio Hale", 855, 704));
        players.add(new SamplePlayer("Erin Goodwin", 335, 829));
        players.add(new SamplePlayer("Bethany Johnson", 567, 652));
        players.add(new SamplePlayer("Leah Patton", 17, 884));
        players.add(new SamplePlayer("Merle Hansen", 752, 315));
        players.add(new SamplePlayer("Jennifer Love", 803, 440));
        players.add(new SamplePlayer("Christy Berry", 372, 90));
        players.add(new SamplePlayer("Nick Mccoy", 703, 895));
        players.add(new SamplePlayer("Candace Hawkins", 767, 278));
        players.add(new SamplePlayer("Mamie Spencer", 803, 523));
        players.add(new SamplePlayer("Ruby Zimmerman", 743, 934));
        players.add(new SamplePlayer("Doris Harrison", 279, 61));
        players.add(new SamplePlayer("Michelle Fisher", 715, 683));
        players.add(new SamplePlayer("Wade Carter", 863, 72));
        players.add(new SamplePlayer("Dianne Howard", 192, 173));
        players.add(new SamplePlayer("Bernard Wheeler", 708, 445));
        players.add(new SamplePlayer("Paulette Jennings", 134, 316));
        players.add(new SamplePlayer("Kerry Silva", 669, 128));
        players.add(new SamplePlayer("Hilda Terry", 506, 944));
        players.add(new SamplePlayer("Salvatore Hart", 228, 926));
        players.add(new SamplePlayer("Terry Carpenter", 901, 605));
        players.add(new SamplePlayer("Marie Jackson", 739, 842));
        players.add(new SamplePlayer("Alice Reese", 113, 518));
        players.add(new SamplePlayer("Monique Schmidt", 412, 795));
        players.add(new SamplePlayer("Marvin Hubbard", 155, 60));
        players.add(new SamplePlayer("Dexter Estrada", 312, 778));
        players.add(new SamplePlayer("Dianna Obrien", 724, 932));
        players.add(new SamplePlayer("Olga Washington", 367, 709));
        players.add(new SamplePlayer("Lora Brock", 545, 547));
        players.add(new SamplePlayer("Sheldon Hill", 262, 292));
        players.add(new SamplePlayer("Leroy Myers", 187, 798));
        players.add(new SamplePlayer("Jo Park", 999, 949));
        players.add(new SamplePlayer("Bill Ortega", 521, 794));
        players.add(new SamplePlayer("Vicki Rios", 610, 544));
        players.add(new SamplePlayer("Jean Douglas", 417, 4));
        players.add(new SamplePlayer("Harriet Morrison", 882, 417));
        players.add(new SamplePlayer("Ray Lindsey", 109, 607));
        players.add(new SamplePlayer("Tom Greene", 130, 781));
        players.add(new SamplePlayer("Nicholas Davidson", 482, 432));
        players.add(new SamplePlayer("Ronald Castillo", 861, 354));
        players.add(new SamplePlayer("Robin Jefferson", 204, 431));
        players.add(new SamplePlayer("Frances Summers", 549, 672));
        players.add(new SamplePlayer("Debbie Cox", 246, 332));
        players.add(new SamplePlayer("Christian Warren", 188, 510));
        players.add(new SamplePlayer("Kristopher Turner", 0, 0));
        players.add(new SamplePlayer("Oscar Houston", 286, 171));
        players.add(new SamplePlayer("Charlie Webb", 204, 383));
        players.add(new SamplePlayer("Todd Montgomery", 712, 914));
        players.add(new SamplePlayer("Irving Franklin", 346, 62));
        players.add(new SamplePlayer("Jacob Brown", 1, 337));
        players.add(new SamplePlayer("Jermaine Sandoval", 39, 910));
        players.add(new SamplePlayer("Jeannette Francis", 966, 318));
        players.add(new SamplePlayer("Brian Dunn", 726, 532));
        players.add(new SamplePlayer("Brandon Walsh", 108, 477));
        players.add(new SamplePlayer("Adrian Griffin", 572, 596));
        players.add(new SamplePlayer("Martha Pierce", 774, 995));
        players.add(new SamplePlayer("Estelle Mendoza", 991, 674));
        players.add(new SamplePlayer("Mary Blake", 103, 552));
        players.add(new SamplePlayer("Alberto Watts", 65, 748));
        players.add(new SamplePlayer("Kent Johnston", 609, 205));
        players.add(new SamplePlayer("Clifton Mendez", 652, 562));
        players.add(new SamplePlayer("Conrad Stanley", 228, 74));
        return players;
    }

    /** Get a valid list of players for convenience of testing */
    public static List<Player> getPlayers(){
    	ArrayList<Player> players = new ArrayList<Player>();
    	
    	for(SamplePlayer samplePlayer : getSamplePlayers())
    		try {
    			players.add(new Player(samplePlayer.getName(), samplePlayer.getWins(), samplePlayer.getLosses(), samplePlayer.getLevel()));
    		} catch (PlayerFormatException e) {
    			continue;
    		}
    
    	return players;
    }
}
